export const ComponentListData = [
  { urlLink: "spacing", urlName: "Spacing" },
  { urlLink: "colors", urlName: "Colors" },
  { urlLink: "inlineAlert", urlName: "Inline Alert" },
  { urlLink: "fullWidthAlert", urlName: "Full Width Alert" },
  { urlLink: "elevation", urlName: "Elevation" },
  { urlLink: "typography", urlName: "Typography (Related to fonts)" },
  { urlLink: "border", urlName: "Border (Radius, Width, Style)" },
  { urlLink: "icon", urlName: "Icon" },
  { urlLink: "fileUpload", urlName: "File Upload" },
  { urlLink: "inputField", urlName: "Input Fields" },
  { urlLink: "loader", urlName: "Loader" },
  { urlLink: "menu", urlName: "Menu" },
  { urlLink: "pagination", urlName: "Pagination" },
  { urlLink: "paginationBar", urlName: "Pagination bar" },
  { urlLink: "radio", urlName: "Radio" },
  { urlLink: "switch", urlName: "Switch" },
  { urlLink: "stepper", urlName: "Stepper" },
  { urlLink: "textArea", urlName: "Text area" },
  { urlLink: "table", urlName: "Table" },
  { urlLink: "toast", urlName: "Toast" },
  { urlLink: "tabBar", urlName: "Tab bar" },
  { urlLink: "videoPlayer", urlName: "Video Player" },
  { urlLink: "accordion", urlName: "Accordion" },
  { urlLink: "avatar", urlName: "Avatar" },
  { urlLink: "fullWidth", urlName: "Full Width" },
  { urlLink: "badge", urlName: "Badge" },
  { urlLink: "breadcrumb", urlName: "Breadcrumbs" },
  { urlLink: "buttons", urlName: "Buttons" },
  { urlLink: "chips", urlName: "Chips" },
  { urlLink: "checkbox", urlName: "Check box" },
  { urlLink: "chart", urlName: "Chart" },
];
